name: rest-app-dev
services:
  rest-api-service:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile-dev
    image: hazardsoft/library-rest-api:latest
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - rest-logs:/app/logs
    env_file:
      - .env.docker
    depends_on:
      - database-service
  database-service:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: hazardsoft/library-database:latest
    command: '-c log_statement=all -c logging_collector=on -c log_directory=/var/lib/postgresql/log -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-logs:/var/lib/postgresql/log
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pg-data:
    name: pg-data
  pg-logs:
    name: pg-logs
  rest-logs:
    name: rest-logs
